//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorToDoApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorToDoApp.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Todos.
        /// </summary>
        public static string Active_Todos {
            get {
                return ResourceManager.GetString("Active Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Connection_failed {
            get {
                return ResourceManager.GetString("Connection failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete all bin tasks.
        /// </summary>
        public static string Couldn_t_delete_all_bin_tasks {
            get {
                return ResourceManager.GetString("Couldn\'t delete all bin tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete your todo. Please try again!.
        /// </summary>
        public static string Couldn_t_delete_your_todo__Please_try_again_ {
            get {
                return ResourceManager.GetString("Couldn\'t delete your todo. Please try again!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE A NEW TODO.
        /// </summary>
        public static string CREATE_A_NEW_TODO {
            get {
                return ResourceManager.GetString("CREATE A NEW TODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT TODO.
        /// </summary>
        public static string EDIT_TODO {
            get {
                return ResourceManager.GetString("EDIT TODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEY THERE.
        /// </summary>
        public static string HEY_THERE {
            get {
                return ResourceManager.GetString("HEY THERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover for your statistics!.
        /// </summary>
        public static string Hover_for_your_statistics_ {
            get {
                return ResourceManager.GetString("Hover for your statistics!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Complete?.
        /// </summary>
        public static string Is_Complete_ {
            get {
                return ResourceManager.GetString("Is Complete?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading task....
        /// </summary>
        public static string Loading_todos___ {
            get {
                return ResourceManager.GetString("Loading todos...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string LOG_IN {
            get {
                return ResourceManager.GetString("LOG IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY TODOS.
        /// </summary>
        public static string MY_TODOS {
            get {
                return ResourceManager.GetString("MY TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No todos found..
        /// </summary>
        public static string No_todos_found_ {
            get {
                return ResourceManager.GetString("No todos found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDING.
        /// </summary>
        public static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIOUS.
        /// </summary>
        public static string PREVIOUS {
            get {
                return ResourceManager.GetString("PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECYCLE BIN.
        /// </summary>
        public static string RECYCLE_BIN {
            get {
                return ResourceManager.GetString("RECYCLE BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        public static string Recycle_Bin_lttl {
            get {
                return ResourceManager.GetString("Recycle Bin lttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        public static string Something_went_wrong___ {
            get {
                return ResourceManager.GetString("Something went wrong...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong... Please try again!.
        /// </summary>
        public static string Something_went_wrong____Please_try_again_ {
            get {
                return ResourceManager.GetString("Something went wrong... Please try again!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created your todo!.
        /// </summary>
        public static string Successfully_created_your_todo_ {
            get {
                return ResourceManager.GetString("Successfully created your todo!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated your todo!.
        /// </summary>
        public static string Successfully_updated_your_todo_ {
            get {
                return ResourceManager.GetString("Successfully updated your todo!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully cleared your recycling bin!.
        /// </summary>
        public static string Sucessfully_cleared_your_recycling_bin_ {
            get {
                return ResourceManager.GetString("Sucessfully cleared your recycling bin!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully deleted your todo!.
        /// </summary>
        public static string Sucessfully_deleted_your_todo_ {
            get {
                return ResourceManager.GetString("Sucessfully deleted your todo!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully moved your todo into the active todos!.
        /// </summary>
        public static string Sucessfully_moved_your_todo_into_the_active_todos_ {
            get {
                return ResourceManager.GetString("Sucessfully moved your todo into the active todos!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully moved your todo into the recycling bin!.
        /// </summary>
        public static string Sucessfully_moved_your_todo_into_the_recycling_bin_ {
            get {
                return ResourceManager.GetString("Sucessfully moved your todo into the recycling bin!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        public static string TODAY {
            get {
                return ResourceManager.GetString("TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        public static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos can&apos;t be found..
        /// </summary>
        public static string Todo_can_t_be_found_ {
            get {
                return ResourceManager.GetString("Todo can\'t be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos are loading....
        /// </summary>
        public static string Todos_are_loading___ {
            get {
                return ResourceManager.GetString("Todos are loading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos in Recycle Bin.
        /// </summary>
        public static string Todos_in_Recycle_Bin {
            get {
                return ResourceManager.GetString("Todos in Recycle Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOMORROW.
        /// </summary>
        public static string TOMORROW {
            get {
                return ResourceManager.GetString("TOMORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your tasks..
        /// </summary>
        public static string Track_your_tasks_ {
            get {
                return ResourceManager.GetString("Track your tasks.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to see this Site. Please.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string Unauthorized2 {
            get {
                return ResourceManager.GetString("Unauthorized2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YESTERDAY.
        /// </summary>
        public static string YESTERDAY {
            get {
                return ResourceManager.GetString("YESTERDAY", resourceCulture);
            }
        }
    }
}
